# Generated by Django 2.2 on 2020-07-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_grape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grape',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grapes_that_belongs_to', to='first_app.Region'),
        ),
    ]
